# Generated by Django 3.2.5 on 2022-03-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdKriteria', models.CharField(max_length=20)),
                ('namaKriteria', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_data_kriteria',
            },
        ),
        migrations.CreateModel(
            name='dataNilaiKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdNilai', models.CharField(max_length=80)),
                ('kdKriteria', models.CharField(max_length=20)),
                ('nilai', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_data_nilai_kriteria',
            },
        ),
        migrations.CreateModel(
            name='dataSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_data_siswa',
            },
        ),
    ]
