# Generated by Django 3.2.5 on 2022-04-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_datalatih'),
    ]

    operations = [
        migrations.CreateModel(
            name='nilaiGain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaGain', models.CharField(max_length=80)),
                ('nilaiGain', models.FloatField(max_length=40)),
            ],
            options={
                'db_table': 'tbl_nilai_gain',
            },
        ),
    ]
